#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
service nginx start
