#!/usr/bin/env bash
# Configures Nginx server so that /redirect_me is redirecting to another page.

apt-get -y update
apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo sed -i '/^\sserver_name.*/a \        rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
mkdir -p /var/www/error
sudo sed -i '/^\slocation.*/i \        error_page 404 /custom_404.html;' /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" | sudo tee /var/www/error/404.html
service nginx start
